spring:
  ai:
    openai:
      api-key: abcdef
    mistralai:
      api-key: abcded
      chat:
        options:
          model: mistral-large-latest
    ollama:
      base-url: http://localhost:11434
      embedding:
        enable: true
        options:
          model: nomic-embed-text
      chat:
        options:
          model: llama3.2
    vectorstore:
      pgvector:
        initialize-schema: true
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimension: 1536
    mcp:
      client:
        toolcallback:
          enabled: true
      sse:
        connections:
          my-custom-mcp-server:
            url: http://localhost:8081
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
